import Head from "next/head";
import React from "react";
import NavigationBar from "../src/components/NavigationBar";
import ListRequests from "../src/components/Home/ListRequests"
import Footer from "../src/components/Footer";

const HomePage = (props) => {
  return (
    <div className="w-screen h-screen">
      <Head>
        <title>Unstoppable Donations</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <NavigationBar />

      <div className="w-screen min-h-screen flex justify-center">
        <div className="w-[80vw] space-y-[2vh] flex flex-col justify-center py-[4vh]">
          <ListRequests donation={props.donation} />
          <div className="flex flex-col py-3 w-[80vw]">
            <p className="text-center">
              The changing currencies API allows 1 conversion per second, only use if
              needed
            </p>
            <p className="text-center">
              Login to Polygon account if possible to save API calls for users without
              accounts
            </p>
          </div>

          <div className="space-y-[2vh]">
            <div className="w-full h-content py-1 flex flex-col justify-center border-2 drop-shadow-sm rounded-md">
              <h1 className="h-16 flex items-center justify-center text-4xl font-semibold">
                How It Works
              </h1>
              <div className="space-y-[1vh] text-center justify-self-center">
                <h3 className="text-xl font-bold">Option A</h3>

                <p>Create a Request (gas fee)</p>
                <p>Add an Organizer to recieve funds to (gas fee)</p>
                <p>
                  Someone can then contribute to the request by using the provided
                  address to make a manual transaction or contribute through the UI
                  using the connected wallet
                </p>

                <h3 className="text-xl font-bold">Option B</h3>

                <p>Add a username to your connected Polygon address</p>
                <p>
                  Add your other crypto addresses to your profile and share the profile link
                </p>
              </div>
            </div>


            <div className="w-full h-content flex py-1 my-3 flex-col justify-center border-2 drop-shadow-sm rounded-md">
              <h1 className="h-16 flex items-center justify-center text-4xl font-semibold">
                Tips
              </h1>
              <div className="flex flex-col space-y-[1vh] text-center">
                <p>
                  Use a hardware wallet like the Ledger Nano X or Trezor Model T. This
                  ensures that a you own your private keys so a company or exchange
                  can&apos;t block your account from accessing your funds.
                </p>
                <p>
                  Make a brand new wallet to recieve donations to. This will prevent
                  people from seeing your transaction history of your main wallet. If
                  you don&apos;t want to spend the funds from that wallet you can then
                  send the money to a non KYC Exchange to which is usually a general
                  wallet address or use a Third Party before sending money back to you
                  main wallet.
                </p>
                <p>
                  You should make a new address for each donation you are accepting if
                  you are making multiple requests.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div >

      <Footer />
    </div >
  );
};

export default HomePage;
