import Head from "next/head";
import React from "react";
import NavigationBar from "../src/components/NavigationBar";
import Home from "../src/components/Home";
import Footer from "../src/components/Footer";

const HomePage = (props) => {
  return (
    <div>
      <Head>
        <title>Unstoppable Donations</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <NavigationBar />
      <Home donation={props.donation} />
      <Footer />
    </div>
  );
};

export default HomePage;
