import Head from "next/head";
import React from "react";
import NavigationBar from "../src/components/NavigationBar";
import Home from "../src/components/Home";

const HomePage = () => {
  return (
    <div>
      <Head>
        <title>Unstoppable Donations</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <NavigationBar />
      <Home />
    </div>
  );
};

export default HomePage;
